// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/auth/auth_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest represents a user registration request
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientIp      string                 `protobuf:"bytes,5,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RegisterRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *RegisterRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *RegisterRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// RegisterResponse represents a user registration response
type RegisterResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Success   bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error     string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // "username_taken", "email_taken", "invalid_password", etc.
	// Tokens (present on successful registration)
	AccessToken           string `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken          string `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessTokenExpiresAt  int64  `protobuf:"varint,6,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshTokenExpiresAt int64  `protobuf:"varint,7,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	// User info (present on successful registration)
	User          *User `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegisterResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RegisterResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RegisterResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RegisterResponse) GetAccessTokenExpiresAt() int64 {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return 0
}

func (x *RegisterResponse) GetRefreshTokenExpiresAt() int64 {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return 0
}

func (x *RegisterResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// LoginRequest represents a login request
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientIp      string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LoginRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *LoginRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *LoginRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// LoginResponse represents a login response
type LoginResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Success   bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error     string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // "invalid_credentials", "account_locked", "user_not_found", etc.
	// Tokens (only present on successful login)
	AccessToken           string `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken          string `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessTokenExpiresAt  int64  `protobuf:"varint,6,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshTokenExpiresAt int64  `protobuf:"varint,7,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	// User info (only present on successful login)
	User *User `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`
	// Rate limiting info
	RemainingAttempts int32 `protobuf:"varint,9,opt,name=remaining_attempts,json=remainingAttempts,proto3" json:"remaining_attempts,omitempty"`
	RetryAfterSeconds int64 `protobuf:"varint,10,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LoginResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetAccessTokenExpiresAt() int64 {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return 0
}

func (x *LoginResponse) GetRefreshTokenExpiresAt() int64 {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return 0
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResponse) GetRemainingAttempts() int32 {
	if x != nil {
		return x.RemainingAttempts
	}
	return 0
}

func (x *LoginResponse) GetRetryAfterSeconds() int64 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

// LogoutRequest represents a logout request
type LogoutRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AccessToken           string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	UserId                string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InvalidateAllSessions bool                   `protobuf:"varint,4,opt,name=invalidate_all_sessions,json=invalidateAllSessions,proto3" json:"invalidate_all_sessions,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *LogoutRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LogoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LogoutRequest) GetInvalidateAllSessions() bool {
	if x != nil {
		return x.InvalidateAllSessions
	}
	return false
}

// LogoutResponse represents a logout response
type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogoutResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RefreshTokenRequest represents a token refresh request
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// RefreshTokenResponse represents a token refresh response
type RefreshTokenResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Success               bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                 string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	AccessToken           string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessTokenExpiresAt  int64                  `protobuf:"varint,5,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshTokenExpiresAt int64                  `protobuf:"varint,6,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshTokenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetAccessTokenExpiresAt() int64 {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return 0
}

func (x *RefreshTokenResponse) GetRefreshTokenExpiresAt() int64 {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return 0
}

// ValidateTokenRequest represents a token validation request
type ValidateTokenRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AccessToken         string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RequiredPermissions []string               `protobuf:"bytes,2,rep,name=required_permissions,json=requiredPermissions,proto3" json:"required_permissions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ValidateTokenRequest) GetRequiredPermissions() []string {
	if x != nil {
		return x.RequiredPermissions
	}
	return nil
}

// ValidateTokenResponse represents a token validation response
type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Permissions   []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ValidateTokenResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ValidateTokenResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ValidateTokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// GetUserInfoRequest represents a request to get user info
type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserInfoRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// GetUserInfoResponse represents a response with user info
type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetUserInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetUserInfoResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// ChangePasswordRequest represents a password change request
type ChangePasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	CurrentPassword string                 `protobuf:"bytes,2,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{12}
}

func (x *ChangePasswordRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ChangePasswordRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// ChangePasswordResponse represents a password change response
type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{13}
}

func (x *ChangePasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChangePasswordResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ResetPasswordRequest represents a password reset request
type ResetPasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UsernameOrEmail string                 `protobuf:"bytes,1,opt,name=username_or_email,json=usernameOrEmail,proto3" json:"username_or_email,omitempty"`
	ClientIp        string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{14}
}

func (x *ResetPasswordRequest) GetUsernameOrEmail() string {
	if x != nil {
		return x.UsernameOrEmail
	}
	return ""
}

func (x *ResetPasswordRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

// ResetPasswordResponse represents a password reset response
type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{15}
}

func (x *ResetPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResetPasswordResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResetPasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// VerifyPasswordResetRequest represents a password reset verification request
type VerifyPasswordResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResetToken    string                 `protobuf:"bytes,1,opt,name=reset_token,json=resetToken,proto3" json:"reset_token,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasswordResetRequest) Reset() {
	*x = VerifyPasswordResetRequest{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordResetRequest) ProtoMessage() {}

func (x *VerifyPasswordResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordResetRequest.ProtoReflect.Descriptor instead.
func (*VerifyPasswordResetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{16}
}

func (x *VerifyPasswordResetRequest) GetResetToken() string {
	if x != nil {
		return x.ResetToken
	}
	return ""
}

func (x *VerifyPasswordResetRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// VerifyPasswordResetResponse represents a password reset verification response
type VerifyPasswordResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasswordResetResponse) Reset() {
	*x = VerifyPasswordResetResponse{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordResetResponse) ProtoMessage() {}

func (x *VerifyPasswordResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordResetResponse.ProtoReflect.Descriptor instead.
func (*VerifyPasswordResetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{17}
}

func (x *VerifyPasswordResetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyPasswordResetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetLoginAttemptsRequest represents a request to get login attempts
type GetLoginAttemptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginAttemptsRequest) Reset() {
	*x = GetLoginAttemptsRequest{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginAttemptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginAttemptsRequest) ProtoMessage() {}

func (x *GetLoginAttemptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginAttemptsRequest.ProtoReflect.Descriptor instead.
func (*GetLoginAttemptsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetLoginAttemptsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetLoginAttemptsRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

// GetLoginAttemptsResponse represents a response with login attempts
type GetLoginAttemptsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FailedAttempts    int32                  `protobuf:"varint,1,opt,name=failed_attempts,json=failedAttempts,proto3" json:"failed_attempts,omitempty"`
	AccountLocked     bool                   `protobuf:"varint,2,opt,name=account_locked,json=accountLocked,proto3" json:"account_locked,omitempty"`
	LockedUntil       int64                  `protobuf:"varint,3,opt,name=locked_until,json=lockedUntil,proto3" json:"locked_until,omitempty"`
	RemainingAttempts int32                  `protobuf:"varint,4,opt,name=remaining_attempts,json=remainingAttempts,proto3" json:"remaining_attempts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetLoginAttemptsResponse) Reset() {
	*x = GetLoginAttemptsResponse{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginAttemptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginAttemptsResponse) ProtoMessage() {}

func (x *GetLoginAttemptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginAttemptsResponse.ProtoReflect.Descriptor instead.
func (*GetLoginAttemptsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetLoginAttemptsResponse) GetFailedAttempts() int32 {
	if x != nil {
		return x.FailedAttempts
	}
	return 0
}

func (x *GetLoginAttemptsResponse) GetAccountLocked() bool {
	if x != nil {
		return x.AccountLocked
	}
	return false
}

func (x *GetLoginAttemptsResponse) GetLockedUntil() int64 {
	if x != nil {
		return x.LockedUntil
	}
	return 0
}

func (x *GetLoginAttemptsResponse) GetRemainingAttempts() int32 {
	if x != nil {
		return x.RemainingAttempts
	}
	return 0
}

// HealthResponse represents the health check response
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "unhealthy", "degraded"
	Details       map[string]string      `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{20}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// User represents user information
type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	IsActive        bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsAdmin         bool                   `protobuf:"varint,5,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	IsAuthenticated bool                   `protobuf:"varint,6,opt,name=is_authenticated,json=isAuthenticated,proto3" json:"is_authenticated,omitempty"`
	EmailVerified   bool                   `protobuf:"varint,7,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastLogin       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	Roles           []string               `protobuf:"bytes,11,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions     []string               `protobuf:"bytes,12,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{21}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *User) GetIsAuthenticated() bool {
	if x != nil {
		return x.IsAuthenticated
	}
	return false
}

func (x *User) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

func (x *User) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *User) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// TokenClaims represents JWT token claims
type TokenClaims struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions   []string               `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	ClientId      string                 `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IssuedAt      int64                  `protobuf:"varint,8,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	NotBefore     int64                  `protobuf:"varint,10,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	Issuer        string                 `protobuf:"bytes,11,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience      string                 `protobuf:"bytes,12,opt,name=audience,proto3" json:"audience,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenClaims) Reset() {
	*x = TokenClaims{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenClaims) ProtoMessage() {}

func (x *TokenClaims) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenClaims.ProtoReflect.Descriptor instead.
func (*TokenClaims) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{22}
}

func (x *TokenClaims) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TokenClaims) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TokenClaims) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TokenClaims) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *TokenClaims) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *TokenClaims) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TokenClaims) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TokenClaims) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *TokenClaims) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *TokenClaims) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *TokenClaims) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *TokenClaims) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *TokenClaims) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// AdminActionRequest represents a generic admin action request
type AdminActionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AdminToken     string                 `protobuf:"bytes,1,opt,name=admin_token,json=adminToken,proto3" json:"admin_token,omitempty"`
	TargetUsername string                 `protobuf:"bytes,2,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminActionRequest) Reset() {
	*x = AdminActionRequest{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminActionRequest) ProtoMessage() {}

func (x *AdminActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminActionRequest.ProtoReflect.Descriptor instead.
func (*AdminActionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{23}
}

func (x *AdminActionRequest) GetAdminToken() string {
	if x != nil {
		return x.AdminToken
	}
	return ""
}

func (x *AdminActionRequest) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

// AdminActionResponse represents a generic admin action response
type AdminActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminActionResponse) Reset() {
	*x = AdminActionResponse{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminActionResponse) ProtoMessage() {}

func (x *AdminActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminActionResponse.ProtoReflect.Descriptor instead.
func (*AdminActionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{24}
}

func (x *AdminActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminActionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AdminActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ResetPasswordAdminRequest represents an admin password reset request
type ResetPasswordAdminRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AdminToken     string                 `protobuf:"bytes,1,opt,name=admin_token,json=adminToken,proto3" json:"admin_token,omitempty"`
	TargetUsername string                 `protobuf:"bytes,2,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	NewPassword    string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResetPasswordAdminRequest) Reset() {
	*x = ResetPasswordAdminRequest{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordAdminRequest) ProtoMessage() {}

func (x *ResetPasswordAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordAdminRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordAdminRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{25}
}

func (x *ResetPasswordAdminRequest) GetAdminToken() string {
	if x != nil {
		return x.AdminToken
	}
	return ""
}

func (x *ResetPasswordAdminRequest) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

func (x *ResetPasswordAdminRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// ServerStatsRequest represents a server statistics request
type ServerStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminToken    string                 `protobuf:"bytes,1,opt,name=admin_token,json=adminToken,proto3" json:"admin_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatsRequest) Reset() {
	*x = ServerStatsRequest{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatsRequest) ProtoMessage() {}

func (x *ServerStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatsRequest.ProtoReflect.Descriptor instead.
func (*ServerStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{26}
}

func (x *ServerStatsRequest) GetAdminToken() string {
	if x != nil {
		return x.AdminToken
	}
	return ""
}

// ServerStatsResponse represents a server statistics response
type ServerStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Stats         map[string]string      `protobuf:"bytes,3,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatsResponse) Reset() {
	*x = ServerStatsResponse{}
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatsResponse) ProtoMessage() {}

func (x *ServerStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatsResponse.ProtoReflect.Descriptor instead.
func (*ServerStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_service_proto_rawDescGZIP(), []int{27}
}

func (x *ServerStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServerStatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ServerStatsResponse) GetStats() map[string]string {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_api_proto_auth_auth_service_proto protoreflect.FileDescriptor

const file_api_proto_auth_auth_service_proto_rawDesc = "" +
	"\n" +
	"!api/proto/auth/auth_service.proto\x12\x13dungeongate.auth.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x02\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x1b\n" +
	"\tclient_ip\x18\x05 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgent\x12N\n" +
	"\bmetadata\x18\a \x03(\v22.dungeongate.auth.v1.RegisterRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc8\x02\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x05 \x01(\tR\frefreshToken\x125\n" +
	"\x17access_token_expires_at\x18\x06 \x01(\x03R\x14accessTokenExpiresAt\x127\n" +
	"\x18refresh_token_expires_at\x18\a \x01(\x03R\x15refreshTokenExpiresAt\x12-\n" +
	"\x04user\x18\b \x01(\v2\x19.dungeongate.auth.v1.UserR\x04user\"\xa9\x02\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12K\n" +
	"\bmetadata\x18\x06 \x03(\v2/.dungeongate.auth.v1.LoginRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x03\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x05 \x01(\tR\frefreshToken\x125\n" +
	"\x17access_token_expires_at\x18\x06 \x01(\x03R\x14accessTokenExpiresAt\x127\n" +
	"\x18refresh_token_expires_at\x18\a \x01(\x03R\x15refreshTokenExpiresAt\x12-\n" +
	"\x04user\x18\b \x01(\v2\x19.dungeongate.auth.v1.UserR\x04user\x12-\n" +
	"\x12remaining_attempts\x18\t \x01(\x05R\x11remainingAttempts\x12.\n" +
	"\x13retry_after_seconds\x18\n" +
	" \x01(\x03R\x11retryAfterSeconds\"\xa8\x01\n" +
	"\rLogoutRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x126\n" +
	"\x17invalidate_all_sessions\x18\x04 \x01(\bR\x15invalidateAllSessions\"@\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"W\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"\xfe\x01\n" +
	"\x14RefreshTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x125\n" +
	"\x17access_token_expires_at\x18\x05 \x01(\x03R\x14accessTokenExpiresAt\x127\n" +
	"\x18refresh_token_expires_at\x18\x06 \x01(\x03R\x15refreshTokenExpiresAt\"l\n" +
	"\x14ValidateTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x121\n" +
	"\x14required_permissions\x18\x02 \x03(\tR\x13requiredPermissions\"\xb3\x01\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12-\n" +
	"\x04user\x18\x03 \x01(\v2\x19.dungeongate.auth.v1.UserR\x04user\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\"7\n" +
	"\x12GetUserInfoRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"t\n" +
	"\x13GetUserInfoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12-\n" +
	"\x04user\x18\x03 \x01(\v2\x19.dungeongate.auth.v1.UserR\x04user\"\x88\x01\n" +
	"\x15ChangePasswordRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12)\n" +
	"\x10current_password\x18\x02 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"H\n" +
	"\x16ChangePasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"_\n" +
	"\x14ResetPasswordRequest\x12*\n" +
	"\x11username_or_email\x18\x01 \x01(\tR\x0fusernameOrEmail\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\"a\n" +
	"\x15ResetPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"`\n" +
	"\x1aVerifyPasswordResetRequest\x12\x1f\n" +
	"\vreset_token\x18\x01 \x01(\tR\n" +
	"resetToken\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"M\n" +
	"\x1bVerifyPasswordResetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"R\n" +
	"\x17GetLoginAttemptsRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\"\xbc\x01\n" +
	"\x18GetLoginAttemptsResponse\x12'\n" +
	"\x0ffailed_attempts\x18\x01 \x01(\x05R\x0efailedAttempts\x12%\n" +
	"\x0eaccount_locked\x18\x02 \x01(\bR\raccountLocked\x12!\n" +
	"\flocked_until\x18\x03 \x01(\x03R\vlockedUntil\x12-\n" +
	"\x12remaining_attempts\x18\x04 \x01(\x05R\x11remainingAttempts\"\xea\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12J\n" +
	"\adetails\x18\x02 \x03(\v20.dungeongate.auth.v1.HealthResponse.DetailsEntryR\adetails\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\x19\n" +
	"\bis_admin\x18\x05 \x01(\bR\aisAdmin\x12)\n" +
	"\x10is_authenticated\x18\x06 \x01(\bR\x0fisAuthenticated\x12%\n" +
	"\x0eemail_verified\x18\a \x01(\bR\remailVerified\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"last_login\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\x12\x14\n" +
	"\x05roles\x18\v \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\f \x03(\tR\vpermissions\x12C\n" +
	"\bmetadata\x18\r \x03(\v2'.dungeongate.auth.v1.User.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe4\x03\n" +
	"\vTokenClaims\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\x12\x1b\n" +
	"\tissued_at\x18\b \x01(\x03R\bissuedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\t \x01(\x03R\texpiresAt\x12\x1d\n" +
	"\n" +
	"not_before\x18\n" +
	" \x01(\x03R\tnotBefore\x12\x16\n" +
	"\x06issuer\x18\v \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\f \x01(\tR\baudience\x12J\n" +
	"\bmetadata\x18\r \x03(\v2..dungeongate.auth.v1.TokenClaims.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\x12AdminActionRequest\x12\x1f\n" +
	"\vadmin_token\x18\x01 \x01(\tR\n" +
	"adminToken\x12'\n" +
	"\x0ftarget_username\x18\x02 \x01(\tR\x0etargetUsername\"_\n" +
	"\x13AdminActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x88\x01\n" +
	"\x19ResetPasswordAdminRequest\x12\x1f\n" +
	"\vadmin_token\x18\x01 \x01(\tR\n" +
	"adminToken\x12'\n" +
	"\x0ftarget_username\x18\x02 \x01(\tR\x0etargetUsername\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"5\n" +
	"\x12ServerStatsRequest\x12\x1f\n" +
	"\vadmin_token\x18\x01 \x01(\tR\n" +
	"adminToken\"\xca\x01\n" +
	"\x13ServerStatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12I\n" +
	"\x05stats\x18\x03 \x03(\v23.dungeongate.auth.v1.ServerStatsResponse.StatsEntryR\x05stats\x1a8\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xcf\f\n" +
	"\vAuthService\x12W\n" +
	"\bRegister\x12$.dungeongate.auth.v1.RegisterRequest\x1a%.dungeongate.auth.v1.RegisterResponse\x12N\n" +
	"\x05Login\x12!.dungeongate.auth.v1.LoginRequest\x1a\".dungeongate.auth.v1.LoginResponse\x12Q\n" +
	"\x06Logout\x12\".dungeongate.auth.v1.LogoutRequest\x1a#.dungeongate.auth.v1.LogoutResponse\x12c\n" +
	"\fRefreshToken\x12(.dungeongate.auth.v1.RefreshTokenRequest\x1a).dungeongate.auth.v1.RefreshTokenResponse\x12f\n" +
	"\rValidateToken\x12).dungeongate.auth.v1.ValidateTokenRequest\x1a*.dungeongate.auth.v1.ValidateTokenResponse\x12`\n" +
	"\vGetUserInfo\x12'.dungeongate.auth.v1.GetUserInfoRequest\x1a(.dungeongate.auth.v1.GetUserInfoResponse\x12i\n" +
	"\x0eChangePassword\x12*.dungeongate.auth.v1.ChangePasswordRequest\x1a+.dungeongate.auth.v1.ChangePasswordResponse\x12f\n" +
	"\rResetPassword\x12).dungeongate.auth.v1.ResetPasswordRequest\x1a*.dungeongate.auth.v1.ResetPasswordResponse\x12x\n" +
	"\x13VerifyPasswordReset\x12/.dungeongate.auth.v1.VerifyPasswordResetRequest\x1a0.dungeongate.auth.v1.VerifyPasswordResetResponse\x12o\n" +
	"\x10GetLoginAttempts\x12,.dungeongate.auth.v1.GetLoginAttemptsRequest\x1a-.dungeongate.auth.v1.GetLoginAttemptsResponse\x12E\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a#.dungeongate.auth.v1.HealthResponse\x12f\n" +
	"\x11UnlockUserAccount\x12'.dungeongate.auth.v1.AdminActionRequest\x1a(.dungeongate.auth.v1.AdminActionResponse\x12f\n" +
	"\x11DeleteUserAccount\x12'.dungeongate.auth.v1.AdminActionRequest\x1a(.dungeongate.auth.v1.AdminActionResponse\x12m\n" +
	"\x11ResetUserPassword\x12..dungeongate.auth.v1.ResetPasswordAdminRequest\x1a(.dungeongate.auth.v1.AdminActionResponse\x12g\n" +
	"\x12PromoteUserToAdmin\x12'.dungeongate.auth.v1.AdminActionRequest\x1a(.dungeongate.auth.v1.AdminActionResponse\x12h\n" +
	"\x13GetServerStatistics\x12'.dungeongate.auth.v1.ServerStatsRequest\x1a(.dungeongate.auth.v1.ServerStatsResponseB(Z&github.com/dungeongate/pkg/api/auth/v1b\x06proto3"

var (
	file_api_proto_auth_auth_service_proto_rawDescOnce sync.Once
	file_api_proto_auth_auth_service_proto_rawDescData []byte
)

func file_api_proto_auth_auth_service_proto_rawDescGZIP() []byte {
	file_api_proto_auth_auth_service_proto_rawDescOnce.Do(func() {
		file_api_proto_auth_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_auth_auth_service_proto_rawDesc), len(file_api_proto_auth_auth_service_proto_rawDesc)))
	})
	return file_api_proto_auth_auth_service_proto_rawDescData
}

var file_api_proto_auth_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_api_proto_auth_auth_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),             // 0: dungeongate.auth.v1.RegisterRequest
	(*RegisterResponse)(nil),            // 1: dungeongate.auth.v1.RegisterResponse
	(*LoginRequest)(nil),                // 2: dungeongate.auth.v1.LoginRequest
	(*LoginResponse)(nil),               // 3: dungeongate.auth.v1.LoginResponse
	(*LogoutRequest)(nil),               // 4: dungeongate.auth.v1.LogoutRequest
	(*LogoutResponse)(nil),              // 5: dungeongate.auth.v1.LogoutResponse
	(*RefreshTokenRequest)(nil),         // 6: dungeongate.auth.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),        // 7: dungeongate.auth.v1.RefreshTokenResponse
	(*ValidateTokenRequest)(nil),        // 8: dungeongate.auth.v1.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),       // 9: dungeongate.auth.v1.ValidateTokenResponse
	(*GetUserInfoRequest)(nil),          // 10: dungeongate.auth.v1.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),         // 11: dungeongate.auth.v1.GetUserInfoResponse
	(*ChangePasswordRequest)(nil),       // 12: dungeongate.auth.v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),      // 13: dungeongate.auth.v1.ChangePasswordResponse
	(*ResetPasswordRequest)(nil),        // 14: dungeongate.auth.v1.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),       // 15: dungeongate.auth.v1.ResetPasswordResponse
	(*VerifyPasswordResetRequest)(nil),  // 16: dungeongate.auth.v1.VerifyPasswordResetRequest
	(*VerifyPasswordResetResponse)(nil), // 17: dungeongate.auth.v1.VerifyPasswordResetResponse
	(*GetLoginAttemptsRequest)(nil),     // 18: dungeongate.auth.v1.GetLoginAttemptsRequest
	(*GetLoginAttemptsResponse)(nil),    // 19: dungeongate.auth.v1.GetLoginAttemptsResponse
	(*HealthResponse)(nil),              // 20: dungeongate.auth.v1.HealthResponse
	(*User)(nil),                        // 21: dungeongate.auth.v1.User
	(*TokenClaims)(nil),                 // 22: dungeongate.auth.v1.TokenClaims
	(*AdminActionRequest)(nil),          // 23: dungeongate.auth.v1.AdminActionRequest
	(*AdminActionResponse)(nil),         // 24: dungeongate.auth.v1.AdminActionResponse
	(*ResetPasswordAdminRequest)(nil),   // 25: dungeongate.auth.v1.ResetPasswordAdminRequest
	(*ServerStatsRequest)(nil),          // 26: dungeongate.auth.v1.ServerStatsRequest
	(*ServerStatsResponse)(nil),         // 27: dungeongate.auth.v1.ServerStatsResponse
	nil,                                 // 28: dungeongate.auth.v1.RegisterRequest.MetadataEntry
	nil,                                 // 29: dungeongate.auth.v1.LoginRequest.MetadataEntry
	nil,                                 // 30: dungeongate.auth.v1.HealthResponse.DetailsEntry
	nil,                                 // 31: dungeongate.auth.v1.User.MetadataEntry
	nil,                                 // 32: dungeongate.auth.v1.TokenClaims.MetadataEntry
	nil,                                 // 33: dungeongate.auth.v1.ServerStatsResponse.StatsEntry
	(*timestamppb.Timestamp)(nil),       // 34: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 35: google.protobuf.Empty
}
var file_api_proto_auth_auth_service_proto_depIdxs = []int32{
	28, // 0: dungeongate.auth.v1.RegisterRequest.metadata:type_name -> dungeongate.auth.v1.RegisterRequest.MetadataEntry
	21, // 1: dungeongate.auth.v1.RegisterResponse.user:type_name -> dungeongate.auth.v1.User
	29, // 2: dungeongate.auth.v1.LoginRequest.metadata:type_name -> dungeongate.auth.v1.LoginRequest.MetadataEntry
	21, // 3: dungeongate.auth.v1.LoginResponse.user:type_name -> dungeongate.auth.v1.User
	21, // 4: dungeongate.auth.v1.ValidateTokenResponse.user:type_name -> dungeongate.auth.v1.User
	21, // 5: dungeongate.auth.v1.GetUserInfoResponse.user:type_name -> dungeongate.auth.v1.User
	30, // 6: dungeongate.auth.v1.HealthResponse.details:type_name -> dungeongate.auth.v1.HealthResponse.DetailsEntry
	34, // 7: dungeongate.auth.v1.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	34, // 8: dungeongate.auth.v1.User.created_at:type_name -> google.protobuf.Timestamp
	34, // 9: dungeongate.auth.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	34, // 10: dungeongate.auth.v1.User.last_login:type_name -> google.protobuf.Timestamp
	31, // 11: dungeongate.auth.v1.User.metadata:type_name -> dungeongate.auth.v1.User.MetadataEntry
	32, // 12: dungeongate.auth.v1.TokenClaims.metadata:type_name -> dungeongate.auth.v1.TokenClaims.MetadataEntry
	33, // 13: dungeongate.auth.v1.ServerStatsResponse.stats:type_name -> dungeongate.auth.v1.ServerStatsResponse.StatsEntry
	0,  // 14: dungeongate.auth.v1.AuthService.Register:input_type -> dungeongate.auth.v1.RegisterRequest
	2,  // 15: dungeongate.auth.v1.AuthService.Login:input_type -> dungeongate.auth.v1.LoginRequest
	4,  // 16: dungeongate.auth.v1.AuthService.Logout:input_type -> dungeongate.auth.v1.LogoutRequest
	6,  // 17: dungeongate.auth.v1.AuthService.RefreshToken:input_type -> dungeongate.auth.v1.RefreshTokenRequest
	8,  // 18: dungeongate.auth.v1.AuthService.ValidateToken:input_type -> dungeongate.auth.v1.ValidateTokenRequest
	10, // 19: dungeongate.auth.v1.AuthService.GetUserInfo:input_type -> dungeongate.auth.v1.GetUserInfoRequest
	12, // 20: dungeongate.auth.v1.AuthService.ChangePassword:input_type -> dungeongate.auth.v1.ChangePasswordRequest
	14, // 21: dungeongate.auth.v1.AuthService.ResetPassword:input_type -> dungeongate.auth.v1.ResetPasswordRequest
	16, // 22: dungeongate.auth.v1.AuthService.VerifyPasswordReset:input_type -> dungeongate.auth.v1.VerifyPasswordResetRequest
	18, // 23: dungeongate.auth.v1.AuthService.GetLoginAttempts:input_type -> dungeongate.auth.v1.GetLoginAttemptsRequest
	35, // 24: dungeongate.auth.v1.AuthService.Health:input_type -> google.protobuf.Empty
	23, // 25: dungeongate.auth.v1.AuthService.UnlockUserAccount:input_type -> dungeongate.auth.v1.AdminActionRequest
	23, // 26: dungeongate.auth.v1.AuthService.DeleteUserAccount:input_type -> dungeongate.auth.v1.AdminActionRequest
	25, // 27: dungeongate.auth.v1.AuthService.ResetUserPassword:input_type -> dungeongate.auth.v1.ResetPasswordAdminRequest
	23, // 28: dungeongate.auth.v1.AuthService.PromoteUserToAdmin:input_type -> dungeongate.auth.v1.AdminActionRequest
	26, // 29: dungeongate.auth.v1.AuthService.GetServerStatistics:input_type -> dungeongate.auth.v1.ServerStatsRequest
	1,  // 30: dungeongate.auth.v1.AuthService.Register:output_type -> dungeongate.auth.v1.RegisterResponse
	3,  // 31: dungeongate.auth.v1.AuthService.Login:output_type -> dungeongate.auth.v1.LoginResponse
	5,  // 32: dungeongate.auth.v1.AuthService.Logout:output_type -> dungeongate.auth.v1.LogoutResponse
	7,  // 33: dungeongate.auth.v1.AuthService.RefreshToken:output_type -> dungeongate.auth.v1.RefreshTokenResponse
	9,  // 34: dungeongate.auth.v1.AuthService.ValidateToken:output_type -> dungeongate.auth.v1.ValidateTokenResponse
	11, // 35: dungeongate.auth.v1.AuthService.GetUserInfo:output_type -> dungeongate.auth.v1.GetUserInfoResponse
	13, // 36: dungeongate.auth.v1.AuthService.ChangePassword:output_type -> dungeongate.auth.v1.ChangePasswordResponse
	15, // 37: dungeongate.auth.v1.AuthService.ResetPassword:output_type -> dungeongate.auth.v1.ResetPasswordResponse
	17, // 38: dungeongate.auth.v1.AuthService.VerifyPasswordReset:output_type -> dungeongate.auth.v1.VerifyPasswordResetResponse
	19, // 39: dungeongate.auth.v1.AuthService.GetLoginAttempts:output_type -> dungeongate.auth.v1.GetLoginAttemptsResponse
	20, // 40: dungeongate.auth.v1.AuthService.Health:output_type -> dungeongate.auth.v1.HealthResponse
	24, // 41: dungeongate.auth.v1.AuthService.UnlockUserAccount:output_type -> dungeongate.auth.v1.AdminActionResponse
	24, // 42: dungeongate.auth.v1.AuthService.DeleteUserAccount:output_type -> dungeongate.auth.v1.AdminActionResponse
	24, // 43: dungeongate.auth.v1.AuthService.ResetUserPassword:output_type -> dungeongate.auth.v1.AdminActionResponse
	24, // 44: dungeongate.auth.v1.AuthService.PromoteUserToAdmin:output_type -> dungeongate.auth.v1.AdminActionResponse
	27, // 45: dungeongate.auth.v1.AuthService.GetServerStatistics:output_type -> dungeongate.auth.v1.ServerStatsResponse
	30, // [30:46] is the sub-list for method output_type
	14, // [14:30] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_proto_auth_auth_service_proto_init() }
func file_api_proto_auth_auth_service_proto_init() {
	if File_api_proto_auth_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_auth_auth_service_proto_rawDesc), len(file_api_proto_auth_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_auth_auth_service_proto_goTypes,
		DependencyIndexes: file_api_proto_auth_auth_service_proto_depIdxs,
		MessageInfos:      file_api_proto_auth_auth_service_proto_msgTypes,
	}.Build()
	File_api_proto_auth_auth_service_proto = out.File
	file_api_proto_auth_auth_service_proto_goTypes = nil
	file_api_proto_auth_auth_service_proto_depIdxs = nil
}
